import { PK_CITIES, findCity } from './cities.js';

/**
 * Well-known areas of the larger cities, by the city's ID, for address forms to suggest: an
 * address's area is where a courier sorts its parcel and where its rider starts asking. For
 * suggestions only, as cities are: customers may type any area, and the lists are far from whole.
 */
export const PK_CITY_AREAS: Readonly<Record<string, readonly string[]>> = Object.freeze({
  karachi: [
    'Clifton',
    'DHA',
    'Saddar',
    'PECHS',
    'Bahadurabad',
    'Tariq Road',
    'Gulshan-e-Iqbal',
    'Gulistan-e-Jauhar',
    'North Nazimabad',
    'Nazimabad',
    'Federal B Area',
    'Gulberg',
    'Liaquatabad',
    'North Karachi',
    'New Karachi',
    'Surjani Town',
    'Buffer Zone',
    'Scheme 33',
    'Gulshan-e-Maymar',
    'Malir',
    'Malir Cantt',
    'Shah Faisal Colony',
    'Model Colony',
    'Korangi',
    'Landhi',
    'Orangi Town',
    'Baldia Town',
    'SITE',
    'Lyari',
    'Kharadar',
    'Garden',
    'Keamari',
    'Mehmoodabad',
    'Defence View',
    'Azizabad',
    'Soldier Bazaar',
    'Karachi Cantt',
    'Bahria Town',
  ],
  lahore: [
    'DHA',
    'Gulberg',
    'Model Town',
    'Johar Town',
    'Faisal Town',
    'Garden Town',
    'Allama Iqbal Town',
    'Township',
    'Wapda Town',
    'Bahria Town',
    'Cantt',
    'Cavalry Ground',
    'Askari',
    'Shadman',
    'Samanabad',
    'Muslim Town',
    'Ichhra',
    'Mozang',
    'Garhi Shahu',
    'Anarkali',
    'Walled City',
    'Shalimar',
    'Mughalpura',
    'Baghbanpura',
    'Harbanspura',
    'Shahdara',
    'Gulshan-e-Ravi',
    'Sabzazar',
    'Islampura',
    'Valencia',
    'Lake City',
    'Raiwind Road',
    'Thokar Niaz Baig',
    'Green Town',
    'EME Society',
    'Paragon City',
    'Bahria Orchard',
  ],
  faisalabad: [
    'D Ground',
    'Peoples Colony',
    'Madina Town',
    'Susan Road',
    'Gulberg',
    'Jinnah Colony',
    'Samanabad',
    'Batala Colony',
    'Millat Town',
    'Civil Lines',
    'Ghanta Ghar',
    'Canal Road',
    'Satiana Road',
    'Jaranwala Road',
    'Sargodha Road',
    'Ghulam Muhammad Abad',
    'Gulistan Colony',
    'Kohinoor Town',
    'Wapda City',
    'Mansoorabad',
    'Abdullahpur',
    'Raza Abad',
  ],
  rawalpindi: [
    'Saddar',
    'Satellite Town',
    'Westridge',
    'Chaklala',
    'Lalazar',
    'Tench Bhatta',
    'Raja Bazar',
    'Peshawar Road',
    'Adiala Road',
    'Gulraiz',
    'Gulistan Colony',
    'Afshan Colony',
    'Morgah',
    'Pindora',
    'Khayaban-e-Sir Syed',
    'Sadiqabad',
    'Muslim Town',
    'Dhok Hassu',
    'Askari',
    'Airport Housing Society',
    'Gulzar-e-Quaid',
    'Bahria Town',
    'DHA',
  ],
  gujranwala: [
    'Model Town',
    'Satellite Town',
    'Peoples Colony',
    'DC Colony',
    'Citi Housing',
    'Wapda Town',
    'Cantt',
  ],
  peshawar: [
    'Hayatabad',
    'University Town',
    'Saddar',
    'Cantt',
    'Gulbahar',
    'Faisal Colony',
    'Tehkal',
    'Warsak Road',
    'Ring Road',
    'Board Bazaar',
    'Dalazak Road',
    'Charsadda Road',
    'Kohat Road',
    'Yakatoot',
    'Hashtnagri',
    'Qissa Khwani',
    'Regi Model Town',
    'DHA',
  ],
  multan: [
    'Cantt',
    'Gulgasht Colony',
    'Bosan Road',
    'Shah Rukn-e-Alam Colony',
    'New Multan',
    'Mumtazabad',
    'Model Town',
    'Wapda Town',
    'Shalimar Colony',
    'Garden Town',
    'Officers Colony',
    'Hussain Agahi',
    'DHA',
  ],
  hyderabad: [
    'Latifabad',
    'Qasimabad',
    'Hirabad',
    'Saddar',
    'Cantt',
    'Citizen Colony',
    'Auto Bhan Road',
    'Paretabad',
    'Hussainabad',
    'Gulistan-e-Sajjad',
  ],
  islamabad: [
    'F-6',
    'F-7',
    'F-8',
    'F-10',
    'F-11',
    'G-6',
    'G-7',
    'G-8',
    'G-9',
    'G-10',
    'G-11',
    'G-13',
    'G-14',
    'G-15',
    'E-7',
    'E-11',
    'I-8',
    'I-9',
    'I-10',
    'D-12',
    'B-17',
    'Blue Area',
    'Bani Gala',
    'Bhara Kahu',
    'Chak Shahzad',
    'Tarlai',
    'Shehzad Town',
    'Golra',
    'DHA',
    'Bahria Town',
    'Gulberg Greens',
  ],
  quetta: [
    'Jinnah Town',
    'Satellite Town',
    'Samungli Road',
    'Cantt',
    'Sariab Road',
    'Brewery Road',
    'Shahbaz Town',
    'Airport Road',
  ],
});

/** The areas to suggest for a city, typed as customers type it; none for a city without a list. */
export function areasOf(city: string): readonly string[] {
  const found = findCity(city);
  return (found && PK_CITY_AREAS[found.id]) ?? [];
}

/** An area an address form suggests, with its city's name while the form has no city. */
export interface AreaSuggestion {
  readonly value: string;
  readonly city: string | null;
}

/**
 * What an address form suggests for its area: the city's areas once it has one; every listed
 * area, each with its city's name, while it has none, since a page without scripts cannot change
 * its suggestions as the city is typed; and none for a town without a list.
 */
export function areaSuggestions(city: string): AreaSuggestion[] {
  if (city.trim() !== '') return areasOf(city).map((value) => ({ value, city: null }));
  return PK_CITIES.flatMap((each) =>
    (PK_CITY_AREAS[each.id] ?? []).map((value) => ({ value, city: each.name })),
  );
}
